### ISSUE TITLE
Query - Search users

### ISSUE THREAD

**Issue by tristanMatthias** [code-mentoring/learn#104]
## The story:
As a **social person** that **wants to find my friends on CM**, I want to **search via a name or email for people I know**

---

## What we should do:
We should **build a `searchUsers` query** so that **users can search for other users (to _eventually_ add them as a friend**.

---

## To be successful we need to:
- [ ] Have a `searchUsers` query
- [ ] Return a list of `User` entities on the result
- [ ] Should allow searching via email
- [ ] Should allow searching via name
- [ ] Contain relevant tests for work done that pass in CI

---

### Query: `searchUsers`
```gql
query ($search: String!) {
  searchUsers(search: $search) {
    id
    firstName
    lastName
    # ...
  }
}
```

**Comment by tristanMatthias** [comment]
@LeeYang2019 this would be a good one for you to jump on with @quimgv

**Comment by LeeYang2019** [comment]
Thanks Tristan
