### ISSUE TITLE
Friends module

### ISSUE THREAD

**Issue by quimgv** [code-mentoring/learn#107]
## The story:
As a **user** that **wants to engage in his learning journey**, I want to **have friends within the community**
---

## What we should do:
We should **build the `Friends` database entity** so that **the user can connect with other users to become friends in the platform**.

---

## To be successful we need to:
- [ ] Build the `Module` entity in the database
- [ ] Has the following properties:
  - [ ] `id`: UUID
  - [ ] `userId1`: UUID
  - [ ] `userId2`: UUID
  - [ ] `since`: date
- [ ] Relevant additions to seed Modules
- [ ] Contain relevant tests for work done that pass in CI

## Schema
[LINK TO SCHEMA ERD](https://dbdocs.io/tristanMatthias/Code_Mentoring?table=Friends&schema=public&view=table_structure)

**Comment by quimgv** [comment]
@tristanMatthias @shaneSheridan  I think issues are not automatically getting closed after merging.

**Comment by tristanMatthias** [comment]
It wasn't linkedd in the PR
