### ISSUE TITLE
User signing out - API

### ISSUE THREAD

**Issue by lanphantastic** [code-mentoring/learn#113]
## The story:

As a **signed-in user** that **wants to sign out**, I want to be able to **click on a button to sign out**.

---

## What we should do:
Build a sign-out mutation that clears the `accessToken` from the `LoginOutput` Type and return a message saying:

> You have signed out!

---

## To be successful we need to:

- [ ] Make a `signOut` query
- [ ] Redirect the signed-out user to the login page
- [ ] Return a boolean indicating if the user has signed out
- [ ] Contain relevant tests for work done that pass in CI

---

### Query: `signOut`
```gql
query {
  signOut # Returns a boolean
}
```
#115

**Comment by tristanMatthias** [comment]
@lanphantastic, depending on how complex you wanna get with this, we could also create a Redis store that adds ALL invalidated tokens (that way you can't log back in with the old token). It could clear them out every half an hour etc. Let me know if that's too much work or not.

**Comment by tristanMatthias** [comment]
I also updated the query to be a `query` not a `mutation`. It will also return a boolean, no need to have the nested message property.

**Comment by shaneSheridan** [comment]
@lanphantastic This is still in To-Do state, can you give me an estimate of when progress will start?

**Comment by lanphantastic** [comment]
Hey @shaneSheridan, I'm probably starting this afternoon and get something going.

**Comment by lanphantastic** [comment]
Hey @tristanMatthias, I think adding all invalidated tokens but not yet expired in Redis is a good idea but it should be a new issue. Probably too much work for me at the moment. 

As for the `query` structure, I'll try to return a boolean when the user signs out.

**Comment by ghost** [comment]
Assigned this to me now.

**Comment by ghost** [comment]
Note: 
Front-end signOut function is located in the Auth container.

All it is doing is removing the JWT token from local storage, clearing cache, and setting status to signed out. The sign out page just calls this function when the sign out button is pressed.

**Comment by ghost** [comment]
@tristanMatthias @raysercast1 @RosoPenaranda  As we discussed, this functionality is working sufficiently for now so I'm closing this Issue.
