### ISSUE TITLE
 Update Installation and Setup in Wiki (Missed part of #109)

### ISSUE THREAD

**Issue by shaneSheridan** [code-mentoring/learn#114]
- Installation and Setup section was removed README.md as expected, but the content was not updated in the Wiki.
- Update step 4 to "4. **Install docker.** This will be needed to run the database locally" 
- Delete step 5

**Comment by heyfranksmile** [comment]
Update Installation and Setup in Wiki 
Fixes #114

Updated step 4 and deleted step 5.
