### ISSUE TITLE
User Signing out - Client

### ISSUE THREAD

**Issue by lanphantastic** [code-mentoring/learn#115]
## The story:

As a **signed-in user** that **wants to sign out**, I want to be able to **click on a button to sign out**.

---

## What we should do:
Build a sign-out button that logs the user out, redirects to the login page and return a message saying:

> You have signed out

---

## To be successful we need to:

- [ ] Make a _Sign Out_ button
- [ ] Redirect the signed-out user to the login page
- [ ] Return a message that the user has signed out
- [ ] Contain relevant tests for work done that pass in CI

---
#113 - Related to the API issue of signing out

**Comment by wzhang66** [comment]
Hi, can I take this issue?

**Comment by lanphantastic** [comment]
Hi @wzhang66. Sure, you can take this issue.

**Comment by shaneSheridan** [comment]
Hi @wzhang66, this is still in To-Do state, can you give me an estimate of when progress will start?

**Comment by wzhang66** [comment]
> Hi @wzhang66, this is still in To-Do state, can you give me an estimate of when progress will start?

Hi Shane, I have encountered some errors. Can you help me with this? I have messaged the error to you via slack. Many thanks for your help

**Comment by wzhang66** [comment]
@shaneSheridan Hi Shane, I have encountered some errors. Can you help me with this? I have messaged the error to you via slack. Many thanks for your help
