### ISSUE TITLE
Character Entity

### ISSUE THREAD

**Issue by NoSoEpicCoder** [code-mentoring/learn#117]
## The story:
As a user that wants to use , I want to be able to use a display name

---

## What we should do:
We should create character entity so that we can have a table.

---

## To be successful we need to:
- Character entity
- Contain relevant tests for work done that pass in CI

---

**Comment by tristanMatthias** [comment]
Hey @NoSoEpicCoder can you edit the story for this? Not sure what it is exactly

**Comment by quimgv** [comment]
Closing this issue as it has been done here #123
