### ISSUE TITLE
Lesson path screen

### ISSUE THREAD

**Issue by mtess88** [code-mentoring/learn#137]
## The story:
As a **user** that ** wants to keep track of my progress through the course**, I want to **visually see how many lessons I have finished and how many I have left**

---

## What we should design:
We should **build a lesson path with detailed hover states for each lesson** so that  **users can quickly see where they are and what they are learning**.
---

## To be successful we need to:
_Check these off as they are completed:_
- [x] Lesson path
- [x] Hover state with lesson details (concepts)
- [x] Distinctive shape between lessons and assignments

---

**Comment by tristanMatthias** [comment]
Done
