### ISSUE TITLE
Story Section

### ISSUE THREAD

**Issue by quimgv** [code-mentoring/learn#150]
## The story:
As a **user** that **wants to start a lesson**, I want to **be able to go through the story section steps before I start that lesson**

<img width="719" alt="Screenshot 2020-05-25 at 08 34 10" src="https://user-images.githubusercontent.com/46815065/82766466-ba6e5d00-9e62-11ea-8d90-83c315fd81ed.png">

---

## Design

[LINK TO FIGMA DESIGN](https://www.figma.com/file/eyk5tQgLhIpyiORYfWxeUh/Learning-App?node-id=1%3A14)

---

**Comment by tristanMatthias** [comment]
Sorry @quimgv , I accidentally duplicated this here #241. Closing this for that as there are a few extra details there
