### ISSUE TITLE
Path List Filter

### ISSUE THREAD

**Issue by ahmedfaaid** [code-mentoring/learn#154]
## The story:
As a user that uses this platform, I want to only see the paths I haven't joined yet when I click to join a new path.

---

## What we should do:
We should provide a GraphQL query that only returns the paths a user hasn't joined yet.

---

## To be successful we need to:
- [x] Fetch all available paths in the database
- [x] Fetch paths the user has currently joined
- [x] Filter and return only paths the user hasn't joined yet
- [x] Contain relevant tests for work done that pass in CI

---

**Comment by tristanMatthias** [comment]
@quimgv, is this done? I had a funny feeling this was part of some of the work you guys did. If not disregard @ahmedfaaid 😄

**Comment by ahmedfaaid** [comment]
@tristanMatthias I already started this. I have so many git merge conflicts so it's slowed me down in trying to test it with the join path modal

**Comment by tristanMatthias** [comment]
Did you pull before you branched?

**Comment by ahmedfaaid** [comment]
Yes I pulled. I'll try a rebase.

**Comment by ahmedfaaid** [comment]
Hi @tristanMatthias since this is just a query, do I still have to write a test for it using jest?

**Comment by tristanMatthias** [comment]
Hey @ahmedfaaid. Yes please. Queries and mutations should especially be tested
