### ISSUE TITLE
Staging environment

### ISSUE THREAD

**Issue by tristanMatthias** [code-mentoring/learn#17]
**Is your feature request related to a problem? Please describe.**
Staging environment needed for:
- General QA testing can be carried out before deploying new releases to `master` branch
- Designers can log into current development version without requiring local environment

**Describe the solution you'd like**
- API in Heroku
- Client in Netlify
- Environments based on `develop` branch.

**Comment by quimgv** [comment]
Hey @tristanMatthias commenting here to be added

**Comment by tristanMatthias** [comment]
@shane215 , we will need to think about how this fits into what you're working on in #7

**Comment by shane215** [comment]
@tristanMatthias Maybe a nightly build of develop branch, for example.

**Comment by tristanMatthias** [comment]
Yes, it will be a build on any merge

**Comment by tristanMatthias** [comment]
Hey @shaneSheridan, you feel like tackling this one? Would be really nice to have a staging env for testing stuff in after a PR merge :)

**Comment by tristanMatthias** [comment]
Ping @shaneSheridan. Would be good to have this for our launch soon 😄

**Comment by ghost** [comment]
I learned how to deploy a simple NodeJS app to Heroku :)

This was a useful guide: 
https://www.freecodecamp.org/news/how-to-deploy-a-nodejs-app-to-heroku-from-github-without-installing-heroku-on-your-machine-433bec770efe/

I'll look into Netlify next.

**Comment by ghost** [comment]
Learned how to deploy a React app to Netlify.
Guide: https://www.netlify.com/blog/2016/09/29/a-step-by-step-guide-deploying-on-netlify/

**Comment by ghost** [comment]
I think that the next steps for me are:
- Log into CM heroku/netlify accounts
- Follow steps to deploy **new site** on each with `develop` branch

**Comment by tristanMatthias** [comment]
Hey @shaneSheridan, glad you got across the tech on this. I just made a couple of fixes and enabled build pipelines so we should be good to go :) 

UI: https://develop--learn-codementoring.netlify.app/
API: https://staging-code-mentoring.herokuapp.com/
