### ISSUE TITLE
Path progress

### ISSUE THREAD

**Issue by tristanMatthias** [code-mentoring/learn#178]
## The story:
As a **learner**, I want to **see my progress on the path I'm on**

---

## What we should do:
We should **return a percentage for myPaths* so that **the user can see how far they are into the path**.

---

## To be successful we need to:
- [ ] Return `progress` on the `myPath` entity
- [ ] Extend the `Path` entity with a `MyPath` entity
- [ ] Contain relevant tests for work done that pass in CI

---

## Query / Mutation structures
Should be available on the `myPaths` query

### Query: `mypaths`
```gql
query {
  myPaths {
    ...
    progress
  }
}
```

**Comment by Ellie-2020** [comment]
@tristanMatthias I would like to take this issue.
