### ISSUE TITLE
Switch paths on client

### ISSUE THREAD

**Issue by tristanMatthias** [code-mentoring/learn#179]
## The story:
As a **learner of multiple paths**, I want to **switch the current path I'm on**

---

## What we should do:
We should **hook up the path selector** so that **it works and switches**.
Use the `Path` Container to switch the path.

---

## To be successful we need to:
_Check these off as they are completed:_
- [ ] User can change path
- [ ] Path is stored in localStorage via the `Path` container

**Comment by suzynakayama** [comment]
I can do this
