### ISSUE TITLE
Document Commit Message & Pull Request Process

### ISSUE THREAD

**Issue by shaneSheridan** [code-mentoring/learn#18]
**Is your feature request related to a problem? Please describe.**
- To create a useful revision history, teams should first agree on a commit message convention to use.
- New contributors don't know how to create a pull request. 

**Describe the solution you'd like**
Update [CONTRIBUTING.md](https://github.com/code-mentoring/learn/blob/master/CONTRIBUTING.md) with conventions for:
- Commit messages
- Pull requests

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by lanphantastic** [comment]
I'll take a look into standardizing the commit messages, pull request process. Also, if possible, add on how to write a user story and its acceptance criteria.

**Comment by shane215** [comment]
@lanphantastic sounds good.

**Comment by shane215** [comment]
@tristanMatthias I don’t have permission to add labels or assignee to issues.

Can you grant me the perms?

**Comment by tristanMatthias** [comment]
@lanphantastic , can we use something like Commit lint with Husky? Perhaps in the Angular style? https://github.com/conventional-changelog/commitlint

**Comment by lanphantastic** [comment]
Cool. I didn't know there is a lint for git commit and git push. I'll take a look into this :)

**Comment by tristanMatthias** [comment]
Yeah its pretty nice. Works well when hooked into Husky's git hooks

**Comment by tristanMatthias** [comment]
Hey @lanphantastic, I merged in #41 . We now have a linting command for the entire project with `yarn lint`. You can add that in to what you're doing with this task 😄

**Comment by tristanMatthias** [comment]
Hey @lanphantastic, what's the status on this one? (Just cleaning up issues atm)

**Comment by lanphantastic** [comment]
Hey, @tristanMatthias I will be pushing my parts later this evening. Finally got some time this evening :)

**Comment by lanphantastic** [comment]
So I ran the command below to install _commitlint_
`yarn add @commitlint/{config-conventional,cli} husky --dev`

I received this following error message:

> error Running this command will add the dependency to the workspace root rather than the workspace itself, which might not be what you want - if you really meant it, make it explicit by running this command again with the -W flag (or --ignore-workspace-root-check).

So I ran the command again with the `-W` flag and this is the following message that I want to ask if the warnings below will become a problem if we continue on:

> WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
> This can impact web performance.
> Assets: 
>   main.b0cfa60cb541ea737247.css (765 KiB)
>   main.js (496 KiB)
> 
> WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
> Entrypoints:
>   main (1.23 MiB)
>       main.b0cfa60cb541ea737247.css
>       main.js
> 
> 
> WARNING in webpack performance recommendations: 
> You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
> For more info visit https://webpack.js.org/guides/code-splitting/
> Child HtmlWebpackCompiler:
>      1 asset
>     Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
>     [0] /Users/lanphan-macbookpro/Desktop/code-mentoring/learn/node_modules/html-webpack-plugin/lib/loader.js!./src/index.html 319 bytes {0} [built]
> Child mini-css-extract-plugin ../../node_modules/css-loader/dist/cjs.js!../../node_modules/postcss-loader/src/index.js??ref--5-2!src/css/base.css:
>     Entrypoint mini-css-extract-plugin = *
>     [0] /Users/lanphan-macbookpro/Desktop/code-mentoring/learn/node_modules/css-loader/dist/cjs.js!/Users/lanphan-macbookpro/Desktop/code-mentoring/learn/node_modules/postcss-loader/src??ref--5-2!./src/css/base.css 829 KiB {0} [built]
>         + 1 hidden module
> lerna success run Ran npm script 'build' in 2 packages in 34.4s:
> lerna success - @code-mentoring/api
> lerna success - @code-mentoring/learn-client
✨  Done in 35.76s.
✨  Done in 55.95s.

**Comment by tristanMatthias** [comment]
As expected @lanphantastic. No problems here
