### ISSUE TITLE
Add more Information about Installing Docker in Wiki

### ISSUE THREAD

**Issue by ghost** [code-mentoring/learn#192]
People need more instruction for installing Docker, particularly on Windows.

- Docker Desktop is the easiest way to install Docker 
(https://www.docker.com/products/docker-desktop)
- Docker Toolbox is for older Mac and Windows systems that do not meet the requirements of Docker Desktop for Mac and Docker Desktop for Windows. E.g. Docker Desktop only supports Windows Enterprise edition so people used Toolbox for Windows Home edition (https://docs.docker.com/toolbox/toolbox_install_windows/)
- In the wiki, step 4 (Install Docker This will be needed to run the database locally) of the project Installation and Setup, should be updated to include more instruction on installing Docker (https://github.com/code-mentoring/learn/wiki#%f0%9f%93%a6-installation-and-setup)

**Comment by vitabyfrank** [comment]
@shaneSheridan 
Can you please close this if the issue has been fixed well? I can't ask for PR because it's wiki 
https://github.com/code-mentoring/learn/wiki
