### ISSUE TITLE
Module display differently with learning status

### ISSUE THREAD

**Issue by Ellie-2020** [code-mentoring/learn#198]
## The story:
As a learner that wants to track the modules on a path, I want to see modules displayed differently with different learning status.

---

## What we should do:
We should build the module component that change the display as the learning status on the module changed. 

---

## To be successful we need to:
_Check these off as they are completed:_
- [ ] merge PathModule and ModuleTree/Module
- [ ] Module display differently according to the learning status on the module

---

## Design

![image](https://user-images.githubusercontent.com/63984120/84075851-cbf74f00-a9a2-11ea-9f2b-482dd52d5d8f.png)

[LINK TO FIGMA DESIGN](https://www.figma.com/file/eyk5tQgLhIpyiORYfWxeUh/Learning-App?node-id=1312%3A2317)

---

**Comment by tristanMatthias** [comment]
Hey @Ellie-2020, just use placeholder icons for the moment btw :)

**Comment by Ellie-2020** [comment]
got you.
