### ISSUE TITLE
FIX UI/ - SC text

### ISSUE THREAD

**Issue by YagoMackay** [code-mentoring/learn#201]
## The story:
As a **developer** that **wants to use Styled components**, I want to **use styled components for the text in our project**

---

## What we should do:
We should **modify the current text.css file** so that **we are using styled components in the project**.

---

## To be successful we need to:
_Check these off as they are completed:_
- [ ] switch the current  text.css to use styled components

---

**Comment by quimgv** [comment]
@YagoMackay Can you move it to in progress if you are working on it please?
