### ISSUE TITLE
Adding me to contributing.md

### ISSUE THREAD

**Issue by podiman** [code-mentoring/learn#208]
Fixed issues (PRs without this will not be accepted)
Fixes #208 

Changes
Adding myself to the contributing list
Name: Mayura Wijeyaratne
Role: Front-end
Slack: @Mayura Wijeyaratne 
Github: @podiman
Weekly Availability : 5 - 10 hours
Joined:  May 2020

**Comment by ahmedfaaid** [comment]
Hi @podiman have you submitted a pull request for this yet?

**Comment by podiman** [comment]
No, I didn't have permissions to push the changes to the repo. So I wasn't able to create a pull request with the changes. Will try it soon again. @ahmedfaaid

**Comment by podiman** [comment]
@ahmedfaaid Was able to create the pull request.

**Comment by ahmedfaaid** [comment]
@podiman okay thats great
