### ISSUE TITLE
FIX/UI - SC TextField

### ISSUE THREAD

**Issue by lanphantastic** [code-mentoring/learn#214]
## The story:
As a **developer**, I want the **textField** to use **styled-components**.

---

## What we should do:
We should **change the current TextField** to **styled-components**.

---

## To be successful we need to:
_Check these off as they are completed:_
- [ ] TextField.tsx uses style-components

**Comment by quimgv** [comment]
@lanphantastic could you please double check this is not what @YagoMackay is already working on issue #201 ? Thanks!

**Comment by lanphantastic** [comment]
@quimgv Oh. From what I see, @YagoMackay is modifying the `text.css` while I'm trying to modify `TextField.tsx`. I believe those two are different unless I misunderstood how the files are interacting with each other.

**Comment by YagoMackay** [comment]
@lanphantastic  and @quimgv  Hi guys! Yes, I just modified `text.css ` not `TextField.tsx` so should be fine to go forward with it! Not really sure about their interaction though...
