### ISSUE TITLE
When a path in local storage that doesn't exist, the page does not redirect you to the correct path.

### ISSUE THREAD

**Issue by wdaimee** [code-mentoring/learn#222]
## The bug relates to:
- [ ] `api` - An issue with the API
- [ ] `ui` - An issue with a UI component
- [x] `client` - An issue with the Client project
- [ ] `admin` - An issue with the Admin project

**Describe the bug**
If there is a path in local storage but it does not exist within the project, the page does not act correctly and does not redirect or display to the correct path.

**To Reproduce**
1. Make sure an incorrect path in stored in local storage
2. Sign In to App

**Expected behavior**
The app should look to see if there is a correct path within local storage. If it finds a path that is not correct, it should delete the path and add the correct path to local storage and display the correct path on the client.

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.4
 - Browser: Chrome
 - Version: 83.0.4103.97

**Comment by tristanMatthias** [comment]
Is this related to #218?

**Comment by wdaimee** [comment]
No, I believe these are separate issues. I think #218 is restricting the welcome page if the onboarding process has completed. The issue in #222 is a bug that does not render the path module after the onboarding process is completed and when the pathId in local storage does not match the pathId in the user's myPaths.
