### ISSUE TITLE
Fix/Client: Alignment for certain elements is off on app header after login

### ISSUE THREAD

**Issue by rjtbansal** [code-mentoring/learn#236]
**Describe the bug**
After login the App Header has a redundant Sign Out button which is non-functional and should be removed as Sign Out functionality is already available in the avatar dropdown. The button gravatar and the CM logo is off alignment as well.

**To Reproduce**
1. Login to the Learn Project
2. Observe the header
 It will look like this:
![image](https://user-images.githubusercontent.com/8683116/85485715-47f2b900-b597-11ea-9235-9ffaee771978.png)

**Expected behavior**
Elements should be aligned as per this mockup and Sign Out button should be removed:
https://www.figma.com/file/eyk5tQgLhIpyiORYfWxeUh/Learning-App?node-id=1%3A104
**Desktop**
 - OS: Windows
 - Browsers: Chrome, Edge, Firefox

**Comment by rjtbansal** [comment]
Need to investigate is it because of styled components migration that is currently going on?

**Comment by tristanMatthias** [comment]
@rjtbansal, while you're at it, you might want to change it to the new design :). Hit up @code-mentoring/design for that

**Comment by rjtbansal** [comment]
@tristanMatthias  definitely!

**Comment by rjtbansal** [comment]
@tristanMatthias  Just to clarify. Do I just check in the part without the Sign Out button first so that it doesn't look misaligned for others who pull in the changes or do it only after updating as per the new design?

**Comment by tristanMatthias** [comment]
Might as well do it all in one go :)

**Comment by rjtbansal** [comment]
Alright PR has been opened though. Will keep on adding commits to that one in that case
