### ISSUE TITLE
UI - App header

### ISSUE THREAD

**Issue by tristanMatthias** [code-mentoring/learn#24]
![image](https://user-images.githubusercontent.com/2550138/79710696-cc714480-8293-11ea-9f99-6342913f5f80.png)

**Is your feature request related to a problem? Please describe.**
As a user I want to navigate across the app easily and see relevant information about my progress in the app.

**Describe the solution you'd like**
A header component needs to be built for the UI. It should follow the designs given in the Figma document 

**Additional context**
Figma designs: https://www.figma.com/file/MfOc0a8Ac9Zoh9RppoEuiD/CM-UI?node-id=0%3A1&viewport=550%2C371%2C0.47890499234199524

Relies on:
- [x] #1 Me GQL Query

**Comment by suzynakayama** [comment]
I can try helping with this one.

**Comment by tristanMatthias** [comment]
Thanks @suzynakayama ! Putting you on this.
Please make sure we add it to the `ui` package :), that way it's obstracted for other projects that want to use it!

**Comment by tristanMatthias** [comment]
@suzynakayama, this will rely on #1. Chat to @quimgv about this as you will need to use the `me` query.

**Comment by quimgv** [comment]
@suzynakayama I just pushed "Me" #38 . As soon as it's merged if it passes @tristanMatthias validation you should be able to query me from the UI. Don't hesitate to ask if you have any question :)

**Comment by suzynakayama** [comment]
@quimgv , thank you!

**Comment by tristanMatthias** [comment]
@suzynakayama this was merged last night FYI 😄

**Comment by suzynakayama** [comment]
@tristanMatthias , yes I was keeping an eye! Thanks! =)
