### ISSUE TITLE
UI - <LessonProgress />

### ISSUE THREAD

**Issue by tristanMatthias** [code-mentoring/learn#242]
## The story:
As a **user going through a lesson** that **wants to know how long I have left**, I want to **easily see how much of a lesson I've completed**

---

## What we should do:
We should **build the `<LessonProgress />`** so that **the user can track their progress in a lesson**.

---

## To be successful we need to:
_Check these off as they are completed:_
- [ ] Should take `max: number` prop
- [ ] Should take `current: number` prop

---

## Design
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/2550138/86183278-ab349c00-baff-11ea-9065-058de917c3bc.png">

[LINK TO FIGMA DESIGN](https://www.figma.com/file/eyk5tQgLhIpyiORYfWxeUh/Learning-App?node-id=1546%3A15)

**Comment by podiman** [comment]
@tristanMatthias I would like some clarification on max and current values. Are they percentage values? or like there are 5 lessons max and user is in lesson 2 ?

**Comment by tristanMatthias** [comment]
This is for a lesson itself. So they will be integers :).

**Comment by podiman** [comment]
@tristanMatthias Right, I did realized that last night, and created a pull request, check it out and let me know what improvements I need to do.
