### ISSUE TITLE
<QuestionResult /> notification - Lesson

### ISSUE THREAD

**Issue by tristanMatthias** [code-mentoring/learn#243]
## The story:
As a **learner** that **wants to know how I did on a question**, I want to **see an explanation of incorrect/correct answers after each question in a lesson**

---

## What we should do:
We should **DO_SOMETHING** so that **THE_GOAL**.

---

## To be successful we need to:
_Check these off as they are completed:_
- [x] Should take prop `state` which can be **either** `'success'` OR `'error'`
- [x] Takes `children` string
- [x] Slides up as animation when entering

---

## Design
<img width="1284" alt="image" src="https://user-images.githubusercontent.com/2550138/86183736-ac19fd80-bb00-11ea-9715-923e385f9fbe.png">
<img width="1368" alt="image" src="https://user-images.githubusercontent.com/2550138/86183765-bc31dd00-bb00-11ea-874d-cc7f814647ca.png">

[LINK TO FIGMA DESIGN](https://www.figma.com/file/eyk5tQgLhIpyiORYfWxeUh/Learning-App?node-id=1546%3A1058)

**Comment by wdaimee** [comment]
Hi Tristan, 

Had a question on this, is the <QuestionResult /> part of the UI or client? My hunch is that it is part of client.

Also, is there a video of how you want the animation for the slide in?

**Comment by tristanMatthias** [comment]
Ah sorry just got to this. No video, just a slide up with a fade. Nothing too fancy!
And yes, part of the `client` as it won't be used anywhere else

**Comment by wdaimee** [comment]
Perfect! Thanks Tristan!
