### ISSUE TITLE
<MemoryGameCard /> - Lesson

### ISSUE THREAD

**Issue by tristanMatthias** [code-mentoring/learn#244]
## The story:
As a **user** that **wants to test my memory**, I want to **play memory game by matching "cards" in a lesson**

---

## What we should do:
We should **build a "flippable" card** so that **the user can play memory games**.

---

## To be successful we need to:
_Check these off as they are completed:_
- [ ] Card should be hidden by default
- [ ] User can click on a card to flip it and reveal the answer (animated in css)
- [ ] Should take prop `flipped` as a boolean
- [ ] Should take prop `state` as either `'correct'` OR `'incorrect`'

---

## Design
Default: 
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/2550138/86184485-521a3780-bb02-11ea-8e66-7e9d72bf1c75.png">

Flipped:
<img width="1217" alt="image" src="https://user-images.githubusercontent.com/2550138/86184530-6827f800-bb02-11ea-9751-20eb70f275ae.png">

Correct:
<img width="628" alt="image" src="https://user-images.githubusercontent.com/2550138/86184559-75dd7d80-bb02-11ea-9e92-b8ee9aee778f.png">

Incorrect:
<img width="633" alt="image" src="https://user-images.githubusercontent.com/2550138/86184606-87bf2080-bb02-11ea-9e34-600abc05aa84.png">

[LINK TO FIGMA DESIGN](https://figma.com)

---

## Notes
This ticket **DOES NOT** include the grid, the game or the lesson. It's JUST the **individual** `<MemoryCard />` component

**Comment by Ellie-2020** [comment]
I assigned this to me
