### ISSUE TITLE
<MemoryClock /> component - Lesson

### ISSUE THREAD

**Issue by tristanMatthias** [code-mentoring/learn#245]
## The story:
As a **learner** that **is timed against a clock**, I want to **feel a sense of urgency as the time runs out for me to complete a memory game**

---

## What we should do:
We should **build a clock component that counts down** so that **user knows how much time is left and rushes to complete the game**.

---

## To be successful we need to:
_Check these off as they are completed:_
- [x] A `<MemoryClock />` component
- [x] Takes a `time` prop as seconds as a number
- [x] Counts down to zero, and notifies the `onDone` prop
- [x] Takes a `onDone` prop as a function callback
- [x] Flashes red 1/second when < 10s left
- [x] Flashes red 2/second when < 5s left
- [x] Flashes red 4/second when < 3s left
- [x] Flashes red 8/second when < 2s left
- [x] Flashes red 16/second when < 1s left

This will create an increasing sense of urgency that gets more and more dramatic. It can be done simply with a CSS class that just changes the "animation-duration".

- [x] Plays a "tick" every 2 seconds
- [x] Plays a "tok" every other 2 seconds

---

## Design
Normal
<img width="252" alt="image" src="https://user-images.githubusercontent.com/2550138/86185461-63644380-bb04-11ea-8771-3948155d6632.png">

Flash
<img width="366" alt="image" src="https://user-images.githubusercontent.com/2550138/86185492-6f500580-bb04-11ea-82b9-6dcd0c37465f.png">

Done
<img width="304" alt="image" src="https://user-images.githubusercontent.com/2550138/86185512-7aa33100-bb04-11ea-92b5-f16317c0060b.png">

[LINK TO FIGMA DESIGN](https://www.figma.com/file/eyk5tQgLhIpyiORYfWxeUh/Learning-App?node-id=1546%3A1216)

---

**Comment by marcos5ilva** [comment]
I would like to get involved in this task.

**Comment by ghost** [comment]
> 
> 
> I would like to get involved in this task.

Assigned to you.
