### ISSUE TITLE
Welcome-people image covers login form

### ISSUE THREAD

**Issue by f-westergren** [code-mentoring/learn#248]
## The bug relates to:
- [ ] `api` - An issue with the API
- [ ] `ui` - An issue with a UI component
- [x] `client` - An issue with the Client project
- [ ] `admin` - An issue with the Admin project

**Describe the bug**
When visiting the login page from a mobile device the welcome-people.svg image covers the login form.

**To Reproduce**
1. Go to 'learn.codementoring.co/login' using a device with a small screen.

**Expected behavior**
The image should either not show on small devices or be behind the form. 

**Screenshots**
![IMG_8645](https://user-images.githubusercontent.com/48532419/86364982-eab9d000-bc46-11ea-9651-6ebe0be88ad2.jpg)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Safari

**Comment by tristanMatthias** [comment]
Good find. Thanks @f-westergren
