### ISSUE TITLE
Have Code Mentoring icon as the favIcon

### ISSUE THREAD

**Issue by podiman** [code-mentoring/learn#251]
## The story:
As a **user** that **accesses the site**, I want to **see the logo of the organization in the tab**

---

## What we should do:
We should **add code mentoring logo** so that **it shows in the tab icon space**.

---

## To be successful we need to:
_Check these off as they are completed:_
- [ ] Show code mentoring logo on the window tab

---

## Design
![image](https://user-images.githubusercontent.com/3611890/86501847-f2729500-bd6a-11ea-8d72-fdb0154d12dd.png)

**Comment by ahmedfaaid** [comment]
@podiman would you be doing this or can I assign myself to this?

**Comment by podiman** [comment]
You can do it no worries. However may be you could request from the design
team an icon with the proper dimensions?

**Comment by ahmedfaaid** [comment]
Okay sounds good

**Comment by akimdesign** [comment]
Here is the 16 x 16 px favicon in png format. Let me know if it works correctly. 
![favicon-05](https://user-images.githubusercontent.com/63213855/86541225-3a172f00-bed9-11ea-98f2-75d067e024f6.png)

**Comment by ahmedfaaid** [comment]
@akimdesign I'll try it out

**Comment by akimdesign** [comment]
![favicon_2-05](https://user-images.githubusercontent.com/63213855/86543267-edd4ea80-beea-11ea-9c44-822ba7ee32a1.png)
