### ISSUE TITLE
Broken link on Login in Production

### ISSUE THREAD

**Issue by LeeYang2019** [code-mentoring/learn#256]
## The bug relates to:
- [ ] `api` - An issue with the API
- [ ] `ui` - An issue with a UI component
- [x ] `client` - An issue with the Client project
- [ ] `admin` - An issue with the Admin project

**Describe the bug**
When the user goes to click login on the homepage, the following ensuing page shows a status 404 error.

**To Reproduce**
1. Go to the homepage in codementoring.co
2. Click on the 'Login' button on the upper right hand corner on the navigation bar.

**Expected behavior**
The expected behavior is the user should be taken to the login page where he or she would then enter in an email and password.

**Screenshots**

**Desktop (please complete the following information):**
![Screen Shot 2020-07-05 at 6 34 53 PM](https://user-images.githubusercontent.com/46943342/86543777-99803980-beef-11ea-8964-4a051701573a.png)

![Screen Shot 2020-07-05 at 6 35 34 PM](https://user-images.githubusercontent.com/46943342/86543783-a00eb100-beef-11ea-9c52-5036b275500e.png)

**Additional context**

**Comment by podiman** [comment]
@LeeYang2019 If I'm not mistaken this is in the WWW project. https://github.com/code-mentoring/www , not this project. 
Am I right @rjtbansal @tristanMatthias  ?

**Comment by tristanMatthias** [comment]
That is correct yes

**Comment by LeeYang2019** [comment]
> That is correct yes

@tristanMatthias , I'm not sure how to fix the issue if its in the www project. I don't believe I have access to the www code.

**Comment by tristanMatthias** [comment]
Ok np. I'll take a look :)

**Comment by podiman** [comment]
I think this issue should be transferred to the WWW project.
