### ISSUE TITLE
Position of text "Leaderboard" and icons in header changes during loading an icon

### ISSUE THREAD

**Issue by TomoyaKuroda** [code-mentoring/learn#258]
## The bug relates to:
- [ ] `api` - An issue with the API
- [ ] `ui` - An issue with a UI component
- [x] `client` - An issue with the Client project
- [ ] `admin` - An issue with the Admin project

**Describe the bug**
After choosing a path, the position of text "Leaderboard" and icons in header changes. I think it's better to keep the position during loading the icon.

**To Reproduce**
1. Go to the dashboard page
2. Click on path icon in the header
3. See error

**Expected behavior**
I want to keep the position during loading the icon. We can probably achieve this by putting a transparent element whose size is the same as the icon.

**Screenshots**
![screenshot1 (2)](https://user-images.githubusercontent.com/31934952/86868444-abeea480-c0a2-11ea-8cb3-472265d364d7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 78

**Comment by wdaimee** [comment]
Hi Tomoya,

I'd be happy to take this issue on!

**Comment by TomoyaKuroda** [comment]
@wdaimee Thank you!

**Comment by tristanMatthias** [comment]
@wdaimee, maybe add a placeholder, grey, circle that's the SAME SIZE as the icon. That way it wouldn't jump around, and would look nice :)

**Comment by wdaimee** [comment]
Sorry this took so long to get to but had sometime to look into this issue. I added a place holder circle that is grey of the same size as the icon. Is the below image what you are looking for when there are no paths?

![Screen Shot 2020-07-16 at 5 28 56 PM](https://user-images.githubusercontent.com/59121923/87724692-dff45480-c789-11ea-9e8d-02f7f9da68c9.png)

**Comment by TomoyaKuroda** [comment]
It looks nice, but I'd like to see how it fits with gif animation or video because I want to see the transition. I can take a look at it if you push the branch though.

**Comment by wdaimee** [comment]
The brach has been pushed under "feature/path-text". I didn't add any animation to the transition so would be good to get feedback on that, will make any necessary changes. One thing I wanted to ask, is it possible to ever had no paths selected? Can a user sign up, go through the onboarding process without selecting a path, and then be redirected to the dashboard?

**Comment by TomoyaKuroda** [comment]
Could you add the same placeholder in the top right area as well where you select a path?
I logged in with an account that didn't have a selected path, finished the onboarding process, and I got a bug as this screenshot. Once I refreshed the page, the problem was solved, but it might cause a bug. Could you try that and check it?
![2020-07-18 155613](https://user-images.githubusercontent.com/31934952/87861009-1065fb00-c910-11ea-9d01-2712cca1b6c3.png)

**Comment by tristanMatthias** [comment]
> is it possible to ever had no paths selected? 

No this will never happen. They should always have a path enabled :)

**Comment by wdaimee** [comment]
> Could you add the same placeholder in the top right area as well where you select a path?
> I logged in with an account that didn't have a selected path, finished the onboarding process, and I got a bug as this screenshot. Once I refreshed the page, the problem was solved, but it might cause a bug. Could you try that and check it?
> ![2020-07-18 155613](https://user-images.githubusercontent.com/31934952/87861009-1065fb00-c910-11ea-9d01-2712cca1b6c3.png)

Yes, I will add the same place holder to the image as well, should have it pushed later today for review.

**Comment by wdaimee** [comment]
> > is it possible to ever had no paths selected?
> 
> No this will never happen. They should always have a path enabled :)

That's what I figured as well. So this place holder will be present during loading of paths which makes sense.

**Comment by wdaimee** [comment]
> Could you add the same placeholder in the top right area as well where you select a path?
> I logged in with an account that didn't have a selected path, finished the onboarding process, and I got a bug as this screenshot. Once I refreshed the page, the problem was solved, but it might cause a bug. Could you try that and check it?
> ![2020-07-18 155613](https://user-images.githubusercontent.com/31934952/87861009-1065fb00-c910-11ea-9d01-2712cca1b6c3.png)

Hi Tomoya, I updated the code to place an empty icon at the top right as well. For some reason, when there are no paths selected after onboarding, the icon doesn't show. I am not exactly sure why at the moment since the myPaths query will come back with an empty array. However, I do think this will suffice as you can see the transition from the empty icon to one of the other icons during loading when there is a path selected. Since there should always be a path selected after onboarding, I think this should be ok. Let me know what you think or any changes you would like to see.

**Comment by TomoyaKuroda** [comment]
Hi @wdaimee 
Thank you! Could you add the empty icon here as well?
![2020-07-19 182743](https://user-images.githubusercontent.com/31934952/87886780-9441e500-c9ed-11ea-8ef9-48ab1ed9cc8a.png)

**Comment by wdaimee** [comment]
Hi @tomoyakuroda absolutely! I think I miss understood your request lol. I'll go ahead and make the change for that area as well. In your opinion, since this icon is being used in multiple places should I create an svg and save it in the icon folder?

**Comment by wdaimee** [comment]
@tomoyakuroda Please take a look when you can regarding the empty icon on the app header. I changed the colour as well of the empty icons to match the background colour of the path selector background.

**Comment by TomoyaKuroda** [comment]
@wdaimee Looks great! Yeah, I think it's better to place it in the icon folder. Thank you a lot!
