### ISSUE TITLE
Difficult to see transparent favicon on dark theme

### ISSUE THREAD

**Issue by TomoyaKuroda** [code-mentoring/learn#265]
## The bug relates to:
- [ ] `api` - An issue with the API
- [x] `ui` - An issue with a UI component
- [x] `client` - An issue with the Client project
- [ ] `admin` - An issue with the Admin project

**Describe the bug**
It's hard to see the current favicon on dark thme.

**To Reproduce**
1. Go to a page
2. See error

**Expected behavior**
It's probably better to add white background inside the circle on favicon.

**Screenshots**
![2020-07-11 193926](https://user-images.githubusercontent.com/31934952/87235834-e14f0700-c3ae-11ea-87b7-27749555ebb7.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 78

**Comment by ahmedfaaid** [comment]
This probably happens because the logo is a png with a transparent background. I will try to find logo with a white background to make it more visible.

**Comment by TomoyaKuroda** [comment]
@ahmedfaaid Thank you!

**Comment by ahmedfaaid** [comment]
![favicon_2-05-solid](https://user-images.githubusercontent.com/42549274/88241909-93ad8680-cc59-11ea-83eb-6458ca7363d3.jpg)
Just ignore this. I just need access to the image on another pc.
