### ISSUE TITLE
API - Gravatar default profile pic for users

### ISSUE THREAD

**Issue by tristanMatthias** [code-mentoring/learn#27]
**Is your feature request related to a problem? Please describe.**
As a user, I want to put names to faces for all other people in the app.

**Describe the solution you'd like**
User profile images should be pulled in from gravatar and provided as a new attribute for the User entity.

**Describe alternatives you've considered**
We could also do uploading of pictures, however that would be more complex and we'd have to store them somewhere.

**Additional context**
Gravatar is a service that aims to be the users icon for all the internet. Services and apps around the internet use it instead of rolling their own profile image system.

**Comment by f-westergren** [comment]
I know it says Front End on my role but I'd still like to take a crack at this. I'd probably need some help getting started though.

**Comment by tristanMatthias** [comment]
No probs mate! I'd start by looking through the gravatar docs. Shouldn't be too difficult, as it's a very common pattern. Should probably be put into the `UserService` on create

**Comment by tristanMatthias** [comment]
Hey @f-westergren! How you doin on this one? (Just cleaning up issues, thought I'd check in)

**Comment by f-westergren** [comment]
Hey @tristanMatthias, thanks for checking in! I've been looking over the gravatar docs but haven't done much more than that yet. It's been a busy week so far but I have assigned time to work on this tonight and this weekend. I'm probably gonna need your help at some point though :) I'll report in with my progress tonight!

**Comment by tristanMatthias** [comment]
Sounds good, let me know :)

**Comment by f-westergren** [comment]
Hey @tristanMatthias, so I've got an idea about how this should be implemented and I've made some changes. I'm just not very familiar with NestJS or Typescript so not sure if I have used the correct syntax etc. Let's talk tomorrow!

**Comment by tristanMatthias** [comment]
No worries mate. You got a PR we can checkout?
