### ISSUE TITLE
Move README.md to Github Wiki

### ISSUE THREAD

**Issue by tristanMatthias** [code-mentoring/learn#28]
**Is your feature request related to a problem? Please describe.**
As a contributer to Project CM, I want to see an organised repository of information regarding how I can help, and how the project works.

**Describe the solution you'd like**
We currently have some basic documentation in the README.md file. This should be moved over to a better system like Github Wiki

**Describe alternatives you've considered**
We can stick with README.md for now, but it will get too big pretty quickly.

**Comment by heyfranksmile** [comment]
@tristanMatthias I can try helping with this one

**Comment by tristanMatthias** [comment]
Thanks @heyfranksmile !
