### ISSUE TITLE
Adding time for failed attempts of the memory match card challenge.

### ISSUE THREAD

**Issue by khangdo2019** [code-mentoring/learn#291]
## The story:
As a fresh leaner that it's annoying and intimidating when you play the memory match card game and keep losing, I want to motivate the learners by adding 15 seconds/per failed attempt.

![4  Story 3](https://user-images.githubusercontent.com/57904307/88883640-d8f62900-d202-11ea-8ab9-1e58c1d0ebe5.PNG)

## What we should do:
We should add 15 seconds to the total time so that users have more time to finish and don't feel annoyed when they keep failing.

## To be successful we need to:
- [ ] Add 15 seconds to the total time when users fail.
- [ ] Let's users try again right after failing

**Comment by ghost** [comment]
This should be designed in line with the overall "failed attempt" logic for lessons.
E.g. perhaps users are allowed 5 failed attempts for questions like in Duolingo, and each failed attempt
simply moves on to the next question.

Closing this for now and it will be considered when designing the overall "failed attempt" logic for lessons.
