### ISSUE TITLE
Windows local development

### ISSUE THREAD

**Issue by tristanMatthias** [code-mentoring/learn#3]
**Describe the bug**
Running the project on windows is currently impossible due to environment variables being hardcoded into npm scripts.

**To Reproduce**
On windows, run `yarn build`

**Expected behavior**
Should build correctly on windows using somthing like [`cross-env`](https://www.npmjs.com/package/cross-env)

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by FrankieLaw** [comment]
I am working it.

**Comment by tristanMatthias** [comment]
@FrankieLaw, closing this due to #2 being merged
