### ISSUE TITLE
Inputting throws error in the console

### ISSUE THREAD

**Issue by TomoyaKuroda** [code-mentoring/learn#307]
## The bug relates to:
- [ ] `api` - An issue with the API
- [ ] `ui` - An issue with a UI component
- [x] `client` - An issue with the Client project
- [ ] `admin` - An issue with the Admin project

**Describe the bug**
When I type something in the input field, it throws error message in the console.
`A component is changing an uncontrolled input of type text to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component.`

**To Reproduce**
1. Go to login page
2. Type something
3. See error

**Expected behavior**
I know it's just warning message, but it would be better to solve it because it's annoying.

**Screenshots**
![2020-08-07 225427](https://user-images.githubusercontent.com/31934952/89700981-fa40ce80-d900-11ea-9672-513ce3aa3ecb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Brave
 - Version V1.11.104

**Comment by tristanMatthias** [comment]
Good call @tomoyakuroda. Maybe we should look at upgrading the form library
