### ISSUE TITLE
Feature/HTML Path Lessons

### ISSUE THREAD

**Issue by suzynakayama** [code-mentoring/learn#319]
## The story:
As a student that wants to learn HTML, I want to have the lessons.

---

## What we should do:
We should create lessons.

---

## To be successful we need to:
- [ ] Create stories for the lessons
- [ ] Create questions for the lessons
- [ ] Contain relevant tests for work done that pass in CI

---

**Comment by wdaimee** [comment]
Hi Suzy, do you need some help with this issue?

**Comment by ghost** [comment]
Hi @suzynakayama,

There's a [Lesson module ](https://github.com/code-mentoring/learn/tree/develop/packages/api/src/Lesson) already, is something more needed from front-end?

Thanks
Shane

**Comment by suzynakayama** [comment]
> Hi @suzynakayama,
> 
> There's a [Lesson module ](https://github.com/code-mentoring/learn/tree/develop/packages/api/src/Lesson) already, is something more needed from front-end?
> 
> Thanks
> Shane

Hi Shane, maybe I didn't named this properly. This is just an issue for creating the HTML lessons that I am working on. Since we keep the lessons in the API, I named as an API feature.

**Comment by suzynakayama** [comment]
> Hi Suzy, do you need some help with this issue?

Hi Waqas! Of course! Anyone interested in helping is very welcome!

**Comment by ghost** [comment]
> 
> 
> > Hi @suzynakayama,
> > There's a [Lesson module ](https://github.com/code-mentoring/learn/tree/develop/packages/api/src/Lesson) already, is something more needed from front-end?
> > Thanks
> > Shane
> 
> Hi Shane, maybe I didn't named this properly. This is just an issue for creating the HTML lessons that I am working on. Since we keep the lessons in the API, I named as an API feature.

Ok makes sense, I see the lesson content in `packages/api/content/`.
