### ISSUE TITLE
API Testing

### ISSUE THREAD

**Issue by tristanMatthias** [code-mentoring/learn#4]
**Is your feature request related to a problem? Please describe.**
As a developer of this project, I want to know if the code I wrote broke anything anywhere in the API.

**Describe the solution you'd like**
Using Jest, to have automated testing on the API setup in Travis CI. It should test all the queries and mutations in the API.

**Comment by NoSoEpicCoder** [comment]
I can take up testing for API. I'm still new to it so I may need a little guidance as to what is expected for automated testing.

**Comment by tristanMatthias** [comment]
No worries @NoSoEpicCoder, and thanks for taking this up! Let's setup a call when you have some time tomorrow. In the meantime, familiarize yourself with Jest and GraphQL
