### ISSUE TITLE
Padding error on LeaderboardWidget

### ISSUE THREAD

**Issue by tristanMatthias** [code-mentoring/learn#49]
**Describe the bug**
There is a spacing issue with multiple users in the `<LeaderboardWidget>` component

**To Reproduce**
1. Login to dashboard
2. Have multiple users in the database
3. See padding error

**Expected behavior**
There should be a small space using the `mb-2` class

**Screenshots**
![image](https://user-images.githubusercontent.com/2550138/79940063-a9c76300-842e-11ea-884d-b265a80c59e1.png)

**Comment by tomoyakuroda** [comment]
I think I can fix it.
