### ISSUE TITLE
API Module - Path

### ISSUE THREAD

**Issue by tristanMatthias** [code-mentoring/learn#5]
**Is your feature request related to a problem? Please describe.**
As a user, I want to signup to a path (like a language in Duolingo). This path should progress me from entry level lessons to advanced lessons of increasing difficulty as I progress.

**Describe the solution you'd like**
- A `Path` entity in the API that has a many to many relationship to `User`
- A `Path` should have:
  - `name` Name of the path (EG: Javascript, HTML, etc)
  - `icon` Link to icon of the path
  - `description` Short paragraph explaining the Path
  - `modules` All `Module` (Not completed) entities that belong to the path

**Comment by quimgv** [comment]
@raysercast1 Pull this branch and have a look https://github.com/code-mentoring/learn/tree/feature/path, we can talk about it later today. I encourage you to add **update** and **delete** path.
