### ISSUE TITLE
Build Error inside apollo.ts

### ISSUE THREAD

**Issue by FrankieLaw** [code-mentoring/learn#51]
**Describe the bug**
During the build process **client package** will generate an error preventing the build.

**To Reproduce**
1. cd into **project/learn**
2. execute **```yarn run build```**
3. The error will appear inside the file apollo.ts

**Expected behavior**
Build smoothly without error

**Screenshots**
![apollo bug](https://user-images.githubusercontent.com/24278524/79986134-91c90100-8479-11ea-903a-f879ca434f1e.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 81.0.4044.113

**Comment by tristanMatthias** [comment]
@FrankieLaw, #50 will fix this. Please review that PR, and if it does, approve it and I'll merge :)
