### ISSUE TITLE
Testing - Disable logging for test cases

### ISSUE THREAD

**Issue by NoSoEpicCoder** [code-mentoring/learn#54]
**Is your feature request related to a problem? Please describe.**
As a developer on PCM, I want to run tests without the seeing the error printed from logs when testing negative flows

**Describe the solution you'd like**
Silence the logs for any test class

**Describe alternatives you've considered**
Currently logs are printing when running tests

**Additional context**

**Comment by tomoyakuroda** [comment]
I may figure out the solution. Is it what you want? I created a custom logger and used it in the TestClient.
![2020-04-26 223033](https://user-images.githubusercontent.com/31934952/80328602-c50ae780-880d-11ea-89f9-9436f8e8335c.png)

**Comment by tristanMatthias** [comment]
Cool @tomoyakuroda! You got a branch to look at?

**Comment by tomoyakuroda** [comment]
I created a new branch in my local machine called feature/disable-logging, and I'm thinking of sending  the pull request.

**Comment by tristanMatthias** [comment]
Yes please! Would love to take a look 👀
