### ISSUE TITLE
Join Path Modal

### ISSUE THREAD

**Issue by tristanMatthias** [code-mentoring/learn#72]
![image](https://user-images.githubusercontent.com/2550138/80330040-1026f980-8812-11ea-8fc3-c78ecc026986.png)

**Is your feature request related to a problem? Please describe.**
As an avid learner, I want to signup to new paths and languages as I progress.

**Describe the solution you'd like**
There should be a modal where a user can signup to more Paths.
- [x] Modal component added to `ui`
- [x] Join Path Modal added to `client`
- [x] Reads paths from the `query paths {}` in `api`
- [x] Button is disabled until user selects a path
- [x] Only one path can be selected

**Additional context**
- Will require a `<Modal />` entity in `ui`
- Designs: https://www.figma.com/file/eyk5tQgLhIpyiORYfWxeUh/Learning-App?node-id=197%3A0

**Comment by tristanMatthias** [comment]
@ahmedfaaid @FrankieLaw if you two want to work on this together, that might be nice. Otherwise we can find something else for you @ahmedfaaid

**Comment by FrankieLaw** [comment]
I am cool with working with Ahmed.

**Comment by quimgv** [comment]
@FrankieLaw @ahmedfaaid this part is done in #82 . Maybe put a placeholder in the meantime. I'm about to finish that so hopefully you can take it soon when it's merged.
<img width="332" alt="Screenshot 2020-05-04 at 08 37 49" src="https://user-images.githubusercontent.com/46815065/80927657-96c77200-8de2-11ea-8578-b33189e09243.png">

**Comment by ahmedfaaid** [comment]
> @FrankieLaw @ahmedfaaid this part is done in #82 . Maybe put a placeholder in the meantime. I'm about to finish that so hopefully you can take it soon when it's merged.
> <img alt="Screenshot 2020-05-04 at 08 37 49" width="332" src="https://user-images.githubusercontent.com/46815065/80927657-96c77200-8de2-11ea-8578-b33189e09243.png">

Okay will do

**Comment by quimgv** [comment]
@FrankieLaw @ahmedfaaid How is this going? Do you need any help?

**Comment by ahmedfaaid** [comment]
@quimgv We are working on the UI Modal right now. So far we haven't run into any issues yet.

**Comment by ahmedfaaid** [comment]
@quimgv @tristanMatthias We have run into a small road block. When I fetch all paths and try to render each PathIcon, I get a TypeScript error that says
`Type 'string' is not assignable to type '"html" | "css" | "js" | "nodejs" | "react"'.`

**Comment by tristanMatthias** [comment]
That's fine, you can override that to manually type it with the `as` in typescript. EG:

```tsx
import icons from './path-icons/icons';
// ...
<PathIcon icon={path.icon as keyof typeof icons} className="m-auto" />
```

**Comment by ahmedfaaid** [comment]
Okay perfect

**Comment by tristanMatthias** [comment]
Taking this over
