### ISSUE TITLE
DB Model - User preferences

### ISSUE THREAD

**Issue by tristanMatthias** [code-mentoring/learn#78]
**Is your feature request related to a problem? Please describe.**
As a regular user of PCM, I want to save my preferences.

**Describe the solution you'd like**
There should be a DB model for User preferences (One to One relationship) with properties:
- [ ] `userId` (UUID)
- [ ] `practiceGoal` (Number 1-4)
- [ ] `why` (Text field of why they are here)

The `UserService` should be appended to include:
- [ ] An `updatePreferences` method to set the user's preferences.

**Additional context**
- This model will be used by the `updatePreferences` mutation

**Comment by Ellie-2020** [comment]
@tristanMatthias , I feel that I can take this task. It may take a little bit longer time for me to do it since I will do it while learning.

**Comment by tristanMatthias** [comment]
Ok no problems. I'll team you up with @quimgv to help guide you through this process.
