### ISSUE TITLE
UI Component - Slider

### ISSUE THREAD

**Issue by tristanMatthias** [code-mentoring/learn#81]
## The story:
As a **user**, I want to **easily adjust a number value**

---

## What we should do:
We should **build a slider ui component** so that **range values can be visually identified**.

---

## To be successful we need to:
_Check these off as they are completed:_
- [ ] `<Slider />` element is exposed in the `ui` package
- [ ] Allows for `onChange` property to notify if value changes
- [ ] Takes `min` property as number
- [ ] Takes `max` property as number
- [ ] Takes `steps` property as number to determine distance between values

---

## Design
![image](https://user-images.githubusercontent.com/2550138/80421921-3c428900-88ab-11ea-9a2f-6f18f34ac68d.png)

[LINK TO FIGMA DESIGN](https://www.figma.com/file/4iRXVSBcfJ7WQxYSZNc2FO/Components?node-id=10%3A6)

---

## Other notes
- We may be able to use a library for this. Do some research to see if we can find a good one that we can style as we like

**Comment by quimgv** [comment]
Taking this as I need it for #82 and already doing it there.
