### ISSUE TITLE
Design - Lesson structure

### ISSUE THREAD

**Issue by shaneSheridan** [code-mentoring/learn#83]
Development team requires a general lesson design and structure to guide their implementation, i.e. entities, API, etc.

E.g. Like the lessons in freecodecamp. The completed mark ( ✓ ) and the progress (10/21) showed in this screenshot:
![image](https://user-images.githubusercontent.com/60757762/80435459-90a93100-88ca-11ea-8239-00957d183c11.png)

**Comment by shaneSheridan** [comment]
@tristanMatthias let me know any thoughts on how to approach design.
I'm interested in lesson design, would love to get some of your knowledge/guidance on this issue, including design tools.

**Comment by tristanMatthias** [comment]
This is an entire discipline. Lets do that call soon to discuss.

**Comment by raysercast1** [comment]
@tristanMatthias  @shaneSheridan  let me know when you're going to do the call. I'm interesting too

**Comment by shaneSheridan** [comment]
@tristanMatthias Lesson design structure seems complete here: 
https://dbdiagram.io/d/5eb1c89439d18f5553febe18

Can we close this issue?

**Comment by tristanMatthias** [comment]
No this is a design task, not a dev one. Still needs to be kept open. I’ll bring in the design team for this

**Comment by shaneSheridan** [comment]
@tristanMatthias I unassigned myself from this one, I'll leave it to the design team.

**Comment by tristanMatthias** [comment]
Done
