### ISSUE TITLE
SEEDERS - seed userPreferences when creating users

### ISSUE THREAD

**Issue by quimgv** [code-mentoring/learn#86]
## The story:
As a PCM contributor, I want to have some test users with userPreferences filled. This will help to test cases like onboarding workflow, update user...

## What we should do:
When seeding users, it should seed user preferences using userPreferences service

---

## To be successful we need to:
- [ ] Inject userPreferences service to Seeders.service
- [ ] In seedUsers fn, make that some users have userPreferences populated and some with null

---

## Relies on
- [ ] #78 need to be merged first

**Comment by LeeYang2019** [comment]
Hey @tristanMatthias @quimgv, can I take a stab at this? May take awhile but will get it done.
