### ISSUE TITLE
PathModule component

### ISSUE THREAD

**Issue by tristanMatthias** [code-mentoring/learn#92]
## The story:
As a **learner** that **subscribed to a path**, I want to **view all the lessons and assignments on the path sorted chronologically like Duolingo**

---

## What we should do:
We should **build a small component that takes an icon and label** so that **the user can click on one to go to the lesson/assignment**.

---

## To be successful we need to:
_Check these off as they are completed:_
- [ ] A small `PathModule` component in `client` components
- [ ] Takes the `lesson` prop of the `Lesson` type from the API
- [ ] Takes a prop `state` of values `completed`, `locked` or `open`

---

## Design
![image](https://user-images.githubusercontent.com/2550138/80896041-23294600-8cb8-11ea-9b95-56187e68f099.png)

[LINK TO FIGMA DESIGN](https://www.figma.com/file/eyk5tQgLhIpyiORYfWxeUh/Learning-App?node-id=138%3A0)

**Comment by Ellie-2020** [comment]
Got it.
