### ISSUE TITLE
Module entity

### ISSUE THREAD

**Issue by tristanMatthias** [code-mentoring/learn#96]
## The story:
As a **user** that **wants to learn progressively down a path**, I want to **have my lessons and assignments divided up into small modules I can complete.**
---

## What we should do:
We should **build the `Module` database entity** so that **the user can complete lessons and assignments**.

---

## To be successful we need to:
- [x] Build the `Module` entity in the database
- [x] Has the following properties:
  - [x] `id`: UUID
  - [x] `name`: string
  - [x] `icon`: string
  - [x] `pathId`: reference to a `Path` entity (foreign key contraint)
  - [x] `type`: `"lesson"` OR `"assignment"`
  - [x] `previous`: NULLABLE - reference to another `module` using ID (foreign key constraint)
- [ ] Relevant additions to seed Modules
- [ ] Contain relevant tests for work done that pass in CI

## Schema
[LINK TO SCHEMA ERD](https://dbdiagram.io/d/5eb1c89439d18f5553febe18)

**Comment by NoSoEpicCoder** [comment]
Would the Module table also include the content text? Or would the text be in a .txt file which would be picked up later on.

**Comment by f-westergren** [comment]
Hey, I'm interested in trying to tackle this issue even though it says difficulty: complex :) I'd need some help getting pointed in the right direction though, like where to start and maybe something to read up on.

**Comment by tristanMatthias** [comment]
FYI: I updated the ERD link to https://dbdiagram.io/d/5eb1c89439d18f5553febe18

@NoSoEpicCoder , @f-westergren we can have a chat with @quimgv about this. It's a big one :)
